#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT=$1

if [ -z "$1" ]
then
  echo "ERROR: Must provide a project id as an argument"
  exit 1
fi

gcloud alpha builds submit $DIR --pack image=gcr.io/$PROJECT/callables --project $PROJECT
gcloud run deploy callables --image=gcr.io/$PROJECT/callables --platform managed --region us-central1 --project $PROJECT